### ISSUE TITLE
pandas 2.1.x+ causes a lot of FutureWarnings

### ISSUE THREAD

**Issue by jragbeer** [harryy-he/finqual#1]
Hey, thanks for the great work!

I'm seeing FutureWarning's throughout the project related to new pandas (2.1.x + ) updates,

an example here:

~/python3.10/site-packages/finqual/finqual.py:264: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

 ` fy = df[df["fp"] == "FY"].iloc[-1][7][-2:]`

Will an update be made to this package to accommodate these changes by pandas?

**Comment by harryy-he** [comment]
Hi, thanks for flagging!

I believe I have fixed this now, I have updated the latest [code onto PyPI](https://pypi.org/project/finqual/), so feel free to upgrade to version 1.3.0 via pip - let me know if it still doesn't work!

Thanks,

Harry
